#!/usr/bin/bash

pcs resource create dlm ocf:pacemaker:controld op monitor \
   interval=30s \
   on-fail=fence \
   clone \
   interleave=true \
   ordered=true

pcs resource create clvmd ocf:heartbeat:clvm op monitor \
   interval=30s \
   on-fail=fence \
   clone \
   interleave=true \
   ordered=true


